# Seed Batch Scan Analysis

Грузит батч CSV, даёт фильтры по `ask`, market/expected overpay и разнице между ними, потом печатает результат.

In [15]:
from pathlib import Path

import pandas as pd

In [16]:
RUN_DIR = Path.cwd()
CSV_PATH = RUN_DIR / "data" / "seed_batch_scan_matches.csv"
CSV_PATH

WindowsPath('c:/Roman/skins_roundtrip_v1/steam_seed_scan/seed_batch_scan/data/seed_batch_scan_matches.csv')

In [17]:
df = pd.read_csv(CSV_PATH)
df.shape

(153, 28)

In [18]:
MAX_ASK = 100
MAX_MARKET_OVERPAY_MULT = None
MIN_EXPECTED_OVERPAY_MULT = None
MIN_OVERPAY_GAP_MULT = None
MIN_EDGE_RATIO = 0.3
MIN_CONFIDENCE = None
QUERY_SUBSTRING = ""
ITEM_SUBSTRING = ""

In [19]:
filtered = df.copy()

if MAX_ASK is not None:
    filtered = filtered[filtered["ask"] <= MAX_ASK]
if MAX_MARKET_OVERPAY_MULT is not None:
    filtered = filtered[filtered["market_overpay_mult"] <= MAX_MARKET_OVERPAY_MULT]
if MIN_EXPECTED_OVERPAY_MULT is not None:
    filtered = filtered[filtered["expected_overpay_mult"] >= MIN_EXPECTED_OVERPAY_MULT]
if MIN_OVERPAY_GAP_MULT is not None:
    filtered = filtered[filtered["overpay_gap_mult"] >= MIN_OVERPAY_GAP_MULT]
if MIN_EDGE_RATIO is not None:
    filtered = filtered[filtered["edge_ratio"] >= MIN_EDGE_RATIO]
if MIN_CONFIDENCE is not None:
    filtered = filtered[filtered["overall_confidence"] >= MIN_CONFIDENCE]
if QUERY_SUBSTRING:
    filtered = filtered[filtered["query_name"].str.contains(QUERY_SUBSTRING, case=False, na=False)]
if ITEM_SUBSTRING:
    filtered = filtered[filtered["market_hash_name"].str.contains(ITEM_SUBSTRING, case=False, na=False)]

filtered = filtered.sort_values(["overpay_gap_mult", "edge_abs", "ask"], ascending=[False, False, True], na_position="last").reset_index(drop=True)
filtered.shape

(9, 28)

In [20]:
show_cols = [
    col for col in [
        "query_name",
        "market_hash_name",
        "paint_seed",
        "float_value",
        "ask",
        "base_ask_mean_10",
        "market_overpay_mult",
        "expected_overpay_mult",
        "overpay_gap_mult",
        "edge_abs",
        "edge_ratio",
        "overall_confidence",
        "seed_confidence",
        "listing_id",
    ] if col in filtered.columns
]
filtered[show_cols].sort_values("edge_ratio", ascending = False).head(100)

,query_name,market_hash_name,paint_seed,float_value,ask,base_ask_mean_10,market_overpay_mult,expected_overpay_mult,overpay_gap_mult,edge_abs,edge_ratio,overall_confidence,seed_confidence,listing_id
1,P250 | Mint Kimono,P250 | Mint Kimono (Field-Tested),37,0.264166,12.59,12.214,1.030784,1.6,0.569216,6.9524,0.552216,0.70,0.70,650348605672194094
2,P250 | Mint Kimono,P250 | Mint Kimono (Factory New),83,0.052856,33.87,32.298,1.048672,1.6,0.551328,17.8068,0.525740,0.70,0.70,650347875190563074
3,P250 | Mint Kimono,P250 | Mint Kimono (Factory New),54,0.050805,34.09,32.298,1.055483,1.6,0.544517,17.5868,0.515893,0.70,0.70,626705318029730423
4,AWP | PAW,AWP | PAW (Well-Worn),685,0.436631,3.39,3.210,1.056075,1.6,0.543925,1.7460,0.515044,0.80,0.80,637962976196691967
5,Tec-9 | Ice Cap,Tec-9 | Ice Cap (Field-Tested),261,0.207087,0.50,0.472,1.059322,1.6,0.540678,0.2552,0.510400,0.72,0.72,628957117756224685
6,Tec-9 | Ice Cap,Tec-9 | Ice Cap (Field-Tested),760,0.217253,0.50,0.472,1.059322,1.6,0.540678,0.2552,0.510400,0.72,0.72,641342016870691747
0,XM1014 | Seasons,XM1014 | Seasons (Factory New),115,0.046764,15.00,6.957,2.156102,3.0,0.843898,5.8710,0.391400,0.80,0.80,640216116828246131
7,AWP | Electric Hive,AWP | Electric Hive (Field-Tested),611,0.267285,54.30,42.596,1.274768,1.7,0.425232,18.1132,0.333576,0.80,0.80,648095441393129850
8,P250 | Mint Kimono,P250 | Mint Kimono (Factory New),43,0.067956,39.19,32.298,1.213388,1.6,0.386612,12.4868,0.318622,0.70,0.70,644718375646587095

In [21]:
filtered[show_cols].sort_values("edge_ratio", ascending = False).head(100)

,query_name,market_hash_name,paint_seed,float_value,ask,base_ask_mean_10,market_overpay_mult,expected_overpay_mult,overpay_gap_mult,edge_abs,edge_ratio,overall_confidence,seed_confidence,listing_id
1,P250 | Mint Kimono,P250 | Mint Kimono (Field-Tested),37,0.264166,12.59,12.214,1.030784,1.6,0.569216,6.9524,0.552216,0.70,0.70,650348605672194094
2,P250 | Mint Kimono,P250 | Mint Kimono (Factory New),83,0.052856,33.87,32.298,1.048672,1.6,0.551328,17.8068,0.525740,0.70,0.70,650347875190563074
3,P250 | Mint Kimono,P250 | Mint Kimono (Factory New),54,0.050805,34.09,32.298,1.055483,1.6,0.544517,17.5868,0.515893,0.70,0.70,626705318029730423
4,AWP | PAW,AWP | PAW (Well-Worn),685,0.436631,3.39,3.210,1.056075,1.6,0.543925,1.7460,0.515044,0.80,0.80,637962976196691967
5,Tec-9 | Ice Cap,Tec-9 | Ice Cap (Field-Tested),261,0.207087,0.50,0.472,1.059322,1.6,0.540678,0.2552,0.510400,0.72,0.72,628957117756224685
6,Tec-9 | Ice Cap,Tec-9 | Ice Cap (Field-Tested),760,0.217253,0.50,0.472,1.059322,1.6,0.540678,0.2552,0.510400,0.72,0.72,641342016870691747
0,XM1014 | Seasons,XM1014 | Seasons (Factory New),115,0.046764,15.00,6.957,2.156102,3.0,0.843898,5.8710,0.391400,0.80,0.80,640216116828246131
7,AWP | Electric Hive,AWP | Electric Hive (Field-Tested),611,0.267285,54.30,42.596,1.274768,1.7,0.425232,18.1132,0.333576,0.80,0.80,648095441393129850
8,P250 | Mint Kimono,P250 | Mint Kimono (Factory New),43,0.067956,39.19,32.298,1.213388,1.6,0.386612,12.4868,0.318622,0.70,0.70,644718375646587095